# Generated by Django 6.0.6 on 2026-06-11 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=180, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plantilla de flujo',
                'verbose_name_plural': 'Plantillas de flujos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('terminada', 'Terminada'), ('bloqueada', 'Bloqueada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateTimeField(blank=True, null=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea activa',
                'verbose_name_plural': 'Tareas activas',
                'ordering': ['workflow', 'orden', 'fecha_limite'],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('accion', models.CharField(max_length=80)),
                ('detalle', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='workflows.taskinstance')),
            ],
            options={
                'verbose_name': 'Historial de tarea',
                'verbose_name_plural': 'Historial de tareas',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('comentario', models.TextField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='workflows.taskinstance')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('tarea', 'Tarea'), ('aprobacion', 'Aprobación'), ('hito', 'Hito')], default='tarea', max_length=20)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('duracion_dias', models.PositiveIntegerField(default=1)),
                ('requiere_aprobacion', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('responsable_predeterminado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_responsable', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='workflows.workflowtemplate')),
            ],
            options={
                'verbose_name': 'Tarea de plantilla',
                'verbose_name_plural': 'Tareas de plantilla',
                'ordering': ['workflow', 'orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='plantilla_tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instancias', to='workflows.tasktemplate'),
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_curso', 'En curso'), ('terminado', 'Terminado'), ('pausado', 'Pausado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateTimeField(blank=True, null=True)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instancias', to='workflows.workflowtemplate')),
            ],
            options={
                'verbose_name': 'Flujo activo',
                'verbose_name_plural': 'Flujos activos',
                'ordering': ['-creado'],
            },
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='workflows.workflowinstance'),
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('depende_de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias_salida', to='workflows.tasktemplate')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias_entrada', to='workflows.tasktemplate')),
            ],
            options={
                'verbose_name': 'Dependencia de tarea',
                'verbose_name_plural': 'Dependencias de tareas',
                'constraints': [models.UniqueConstraint(fields=('tarea', 'depende_de'), name='uniq_dependencia_template'), models.CheckConstraint(condition=models.Q(('tarea', models.F('depende_de')), _negated=True), name='no_auto_dependencia_template')],
            },
        ),
        migrations.AddIndex(
            model_name='taskinstance',
            index=models.Index(fields=['workflow', 'estado'], name='workflows_t_workflo_c5cc01_idx'),
        ),
        migrations.AddIndex(
            model_name='taskinstance',
            index=models.Index(fields=['responsable', 'estado'], name='workflows_t_respons_f61cef_idx'),
        ),
        migrations.AddIndex(
            model_name='taskinstance',
            index=models.Index(fields=['fecha_limite'], name='workflows_t_fecha_l_cf629c_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['estado', 'fecha_limite'], name='workflows_w_estado_b4a9c7_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['workflow', 'orden'], name='workflows_t_workflo_d4a1fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='tasktemplate',
            constraint=models.UniqueConstraint(fields=('workflow', 'orden'), name='uniq_orden_por_workflow_template'),
        ),
        migrations.AddConstraint(
            model_name='tasktemplate',
            constraint=models.UniqueConstraint(fields=('workflow', 'nombre'), name='uniq_nombre_tarea_por_workflow_template'),
        ),
    ]
