# Generated by Hermes Agent on 2026-06-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('archivo', models.FileField(upload_to='task_attachments/%Y/%m/')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='workflows.taskinstance')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento adjunto',
                'verbose_name_plural': 'Documentos adjuntos',
                'ordering': ['-creado'],
            },
        ),
    ]
