# Generated by Django 6.0.6 on 2026-06-13 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_taskattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('tarea_atrasada', 'Tarea atrasada'), ('vence_hoy', 'Vence hoy'), ('vence_manana', 'Vence mañana'), ('sin_responsable', 'Sin responsable'), ('tarea_rechazada', 'Tarea rechazada')], max_length=40)),
                ('canal', models.CharField(default='telegram', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_envio', 'En envío'), ('enviada', 'Enviada'), ('fallida', 'Fallida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
                ('asunto', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('fecha_objetivo', models.DateField(blank=True, null=True)),
                ('enviar_despues_de', models.DateTimeField(blank=True, null=True)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('ultimo_intento_en', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_alertas', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='workflows.taskinstance')),
            ],
            options={
                'verbose_name': 'Alerta de workflow',
                'verbose_name_plural': 'Alertas de workflow',
                'ordering': ['estado', 'enviar_despues_de', 'creado'],
                'indexes': [models.Index(fields=['estado', 'canal'], name='workflows_w_estado_454a95_idx'), models.Index(fields=['tipo', 'fecha_objetivo'], name='workflows_w_tipo_c6ac7c_idx'), models.Index(fields=['tarea', 'tipo'], name='workflows_w_tarea_i_c5896d_idx')],
            },
        ),
    ]
