# Generated by Django 5.2.15 on 2026-06-18 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_workflowalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowalert',
            name='tipo',
            field=models.CharField(choices=[('tarea_atrasada', 'Tarea atrasada'), ('vence_hoy', 'Vence hoy'), ('vence_manana', 'Vence mañana'), ('vence_proximamente', 'Vence próximamente'), ('sin_responsable', 'Sin responsable'), ('tarea_rechazada', 'Tarea rechazada')], max_length=40),
        ),
        migrations.CreateModel(
            name='WorkflowAlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('canal_preferido', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email'), ('ambos', 'Telegram + Email')], default='telegram', max_length=20)),
                ('dias_antes_vencimiento', models.PositiveIntegerField(default=1)),
                ('avisar_vencen_hoy', models.BooleanField(default=True)),
                ('avisar_atrasadas', models.BooleanField(default=True)),
                ('repetir_atrasadas_diario', models.BooleanField(default=True)),
                ('avisar_sin_responsable', models.BooleanField(default=True)),
                ('avisar_rechazadas', models.BooleanField(default=True)),
                ('avisar_propietario', models.BooleanField(default=False)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_config', to='workflows.workflowinstance')),
            ],
            options={
                'verbose_name': 'Configuración de alertas',
                'verbose_name_plural': 'Configuraciones de alertas',
            },
        ),
    ]
